In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("healthcare.csv")

In [3]:
dataset.head(5)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
dataset.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
dataset["bmi"].fillna(dataset["bmi"].mean(),inplace=True)

In [6]:
dataset.isnull().any()

id                   False
gender               False
age                  False
hypertension         False
heart_disease        False
ever_married         False
work_type            False
Residence_type       False
avg_glucose_level    False
bmi                  False
smoking_status       False
stroke               False
dtype: bool

In [7]:
x=dataset.iloc[:,1:11].values
y=dataset.iloc[:,11].values

In [8]:
x

array([['Male', 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       ['Female', 61.0, 0, ..., 202.21, 28.893236911794673,
        'never smoked'],
       ['Male', 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       ['Female', 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       ['Male', 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       ['Female', 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [9]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
id                   5110 non-null int64
gender               5110 non-null object
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
ever_married         5110 non-null object
work_type            5110 non-null object
Residence_type       5110 non-null object
avg_glucose_level    5110 non-null float64
bmi                  5110 non-null float64
smoking_status       5110 non-null object
stroke               5110 non-null int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.1+ KB

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0,4,5,6,9])],remainder="passthrough")
#coverts data into binary form
x=ct.fit_transform(x)

In [12]:
x.shape

(5110, 21)

In [13]:
y.shape

(5110,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(10,kernel_initializer ="random_uniform",activation="relu"))

WARNING:tensorflow:From C:\Users\shiva\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [19]:
ann.add(Dense(20,kernel_initializer ="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer ="random_uniform",activation="sigmoid"))

In [21]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

WARNING:tensorflow:From C:\Users\shiva\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/50
4088/4088 [==============================] - 0s 77us/sample - loss: 0.5049 - acc: 0.9477
Epoch 2/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1786 - acc: 0.9523
Epoch 3/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1637 - acc: 0.9523
Epoch 4/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1593 - acc: 0.9523
Epoch 5/50
4088/4088 [==============================] - 0s 37us/sample - loss: 0.1565 - acc: 0.9523
Epoch 6/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1547 - acc: 0.9523
Epoch 7/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1535 - acc: 0.9523
Epoch 8/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1521 - acc: 0.9523
Epoch 9/50
4088/4088 [==============================] - 0s 46us/sample - loss: 0.1510 - acc: 0.9523
Epoch 10/50
4088/4088 [==============================] - 0s 38us/sample - loss: 0.1504 - acc: 0.9523
Epoch 11/50
4088/4088 [==============================] - ETA: 0s - loss: 0.1549 - acc: 0.950 - 0s 35us/sample - loss: 0.1498 - acc: 0.9523
Epoch 12/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1492 - acc: 0.9523
Epoch 13/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1488 - acc: 0.9523
Epoch 14/50
4088/4088 [==============================] - 0s 43us/sample - loss: 0.1483 - acc: 0.9523
Epoch 15/50
4088/4088 [==============================] - 0s 43us/sample - loss: 0.1474 - acc: 0.9523
Epoch 16/50
4088/4088 [==============================] - 0s 41us/sample - loss: 0.1474 - acc: 0.9523
Epoch 17/50
4088/4088 [==============================] - 0s 44us/sample - loss: 0.1473 - acc: 0.9523
Epoch 18/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1468 - acc: 0.9523
Epoch 19/50
4088/4088 [==============================] - 0s 39us/sample - loss: 0.1462 - acc: 0.9523
Epoch 20/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1458 - acc: 0.9523
Epoch 21/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1458 - acc: 0.9523
Epoch 22/50
4088/4088 [==============================] - 0s 43us/sample - loss: 0.1457 - acc: 0.9523
Epoch 23/50
4088/4088 [==============================] - ETA: 0s - loss: 0.1425 - acc: 0.952 - 0s 40us/sample - loss: 0.1450 - acc: 0.9523
Epoch 24/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1449 - acc: 0.9523
Epoch 25/50
4088/4088 [==============================] - 0s 44us/sample - loss: 0.1446 - acc: 0.9523
Epoch 26/50
4088/4088 [==============================] - 0s 46us/sample - loss: 0.1443 - acc: 0.9523
Epoch 27/50
4088/4088 [==============================] - 0s 44us/sample - loss: 0.1441 - acc: 0.9523
Epoch 28/50
4088/4088 [==============================] - 0s 37us/sample - loss: 0.1439 - acc: 0.9523
Epoch 29/50
4088/4088 [==============================] - 0s 40us/sample - loss: 0.1435 - acc: 0.9523
Epoch 30/50
4088/4088 [==============================] - 0s 45us/sample - loss: 0.1434 - acc: 0.9523
Epoch 31/50
4088/4088 [==============================] - 0s 44us/sample - loss: 0.1429 - acc: 0.9523
Epoch 32/50
4088/4088 [==============================] - 0s 48us/sample - loss: 0.1425 - acc: 0.9523
Epoch 33/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1425 - acc: 0.9523
Epoch 34/50
4088/4088 [==============================] - 0s 33us/sample - loss: 0.1416 - acc: 0.9523
Epoch 35/50
4088/4088 [==============================] - 0s 41us/sample - loss: 0.1418 - acc: 0.9523
Epoch 36/50
4088/4088 [==============================] - 0s 45us/sample - loss: 0.1417 - acc: 0.9518
Epoch 37/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1407 - acc: 0.9516
Epoch 38/50
4088/4088 [==============================] - 0s 37us/sample - loss: 0.1409 - acc: 0.9521
Epoch 39/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1405 - acc: 0.9525
Epoch 40/50
4088/4088 [==============================] - 0s 40us/sample - loss: 0.1399 - acc: 0.9521
Epoch 41/50
4088/4088 [==============================] - 0s 41us/sample - loss: 0.1401 - acc: 0.9528
Epoch 42/50
4088/4088 [==============================] - 0s 46us/sample - loss: 0.1393 - acc: 0.9523
Epoch 43/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1393 - acc: 0.9525
Epoch 44/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1387 - acc: 0.9528
Epoch 45/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1384 - acc: 0.9533
Epoch 46/50
4088/4088 [==============================] - 0s 44us/sample - loss: 0.1385 - acc: 0.9528
Epoch 47/50
4088/4088 [==============================] - 0s 45us/sample - loss: 0.1384 - acc: 0.9533
Epoch 48/50
4088/4088 [==============================] - 0s 40us/sample - loss: 0.1384 - acc: 0.9533
Epoch 49/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1378 - acc: 0.9530
Epoch 50/50
4088/4088 [==============================] - 0s 45us/sample - loss: 0.1375 - acc: 0.9533

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred

array([[6.1948538e-01],
       [5.9604645e-08],
       [3.2558739e-02],
       ...,
       [6.5353215e-03],
       [1.4494917e-01],
       [3.1713168e-03]], dtype=float32)

In [27]:
y_test

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [38]:
dataset.head(1500)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.00,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61.00,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,31112,Male,80.00,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49.00,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79.00,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
5,56669,Male,81.00,0,0,Yes,Private,Urban,186.21,29.000000,formerly smoked,1
6,53882,Male,74.00,1,1,Yes,Private,Rural,70.09,27.400000,never smoked,1
7,10434,Female,69.00,0,0,No,Private,Urban,94.39,22.800000,never smoked,1
8,27419,Female,59.00,0,0,Yes,Private,Rural,76.15,28.893237,Unknown,1
9,60491,Female,78.00,0,0,Yes,Private,Urban,58.57,24.200000,Unknown,1
10,12109,Female,81.00,1,0,Yes,Private,Rural,80.43,29.700000,never smoked,1
11,12095,Female,61.00,0,1,Yes,Govt_job,Rural,120.46,36.800000,smokes,1
12,12175,Female,54.00,0,0,Yes,Private,Urban,104.51,27.300000,smokes,1
13,8213,Male,78.00,0,1,Yes,Private,Urban,219.84,28.893237,Unknown,1
14,5317,Female,79.00,0,1,Yes,Private,Urban,214.09,28.200000,never smoked,1
15,58202,Female,50.00,1,0,Yes,Self-employed,Rural,167.41,30.900000,never smoked,1
16,56112,Male,64.00,0,1,Yes,Private,Urban,191.61,37.500000,smokes,1
17,34120,Male,75.00,1,0,Yes,Private,Urban,221.29,25.800000,smokes,1
18,27458,Female,60.00,0,0,No,Private,Urban,89.22,37.800000,never smoked,1
19,25226,Male,57.00,0,1,No,Govt_job,Urban,217.08,28.893237,Unknown,1
20,70630,Female,71.00,0,0,Yes,Govt_job,Rural,193.94,22.400000,smokes,1
21,13861,Female,52.00,1,0,Yes,Self-employed,Urban,233.29,48.900000,never smoked,1
22,68794,Female,79.00,0,0,Yes,Self-employed,Urban,228.70,26.600000,never smoked,1
23,64778,Male,82.00,0,1,Yes,Private,Rural,208.30,32.500000,Unknown,1
24,4219,Male,71.00,0,0,Yes,Private,Urban,102.87,27.200000,formerly smoked,1
25,70822,Male,80.00,0,0,Yes,Self-employed,Rural,104.12,23.500000,never smoked,1
26,38047,Female,65.00,0,0,Yes,Private,Rural,100.98,28.200000,formerly smoked,1
27,61843,Male,58.00,0,0,Yes,Private,Rural,189.84,28.893237,Unknown,1
28,54827,Male,69.00,0,1,Yes,Self-employed,Urban,195.23,28.300000,smokes,1
29,69160,Male,59.00,0,0,Yes,Private,Rural,211.78,28.893237,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1470,52559,Male,18.00,0,0,No,Private,Urban,83.02,40.400000,Unknown,0
1471,937,Male,7.00,0,0,No,children,Urban,87.94,28.893237,Unknown,0
1472,41271,Male,68.00,1,0,Yes,Govt_job,Urban,222.29,30.100000,never smoked,0
1473,66893,Male,49.00,1,0,Yes,Govt_job,Urban,139.43,40.200000,formerly smoked,0
1474,21491,Female,80.00,0,0,Yes,Private,Urban,213.11,34.700000,never smoked,0
1475,51806,Male,31.00,0,0,Yes,Private,Rural,77.23,25.900000,smokes,0
1476,59412,Female,25.00,0,0,Yes,Private,Urban,58.48,23.700000,never smoked,0
1477,742,Female,39.00,0,0,No,Govt_job,Rural,87.33,34.300000,never smoked,0
1478,42902,Male,35.00,0,0,Yes,Private,Rural,102.34,34.300000,never smoked,0
1479,43059,Female,71.00,0,0,Yes,Self-employed,Rural,151.30,26.300000,never smoked,0
1480,61512,Female,71.00,0,0,Yes,Self-employed,Urban,144.23,22.100000,formerly smoked,0
1481,10943,Female,40.00,0,0,Yes,Govt_job,Rural,110.60,33.300000,formerly smoked,0
1482,11447,Female,41.00,0,0,Yes,Govt_job,Urban,80.28,37.300000,never smoked,0
1483,29233,Male,2.00,0,0,No,children,Rural,111.02,20.500000,Unknown,0
1484,17762,Female,3.00,0,0,No,children,Rural,114.88,19.100000,Unknown,0
1485,46284,Male,53.00,1,0,Yes,Self-employed,Urban,227.51,34.700000,formerly smoked,0
1486,1405,Male,1.88,0,0,No,children,Urban,111.65,16.300000,Unknown,0
1487,38493,Male,60.00,1,1,Yes,Private,Urban,201.01,28.000000,never smoked,0
1488,57953,Female,5.00,0,0,No,children,Urban,129.01,17.200000,Unknown,0
1489,30746,Female,30.00,0,0,Yes,Private,Rural,124.08,41.100000,Unknown,0
1490,16949,Female,49.00,1,0,Yes,Govt_job,Rural,107.91,25.000000,Unknown,0
1491,45297,Male,68.00,1,0,Yes,Private,Rural,95.40,27.500000,never smoked,0
1492,40251,Female,23.00,0,0,No,Private,Rural,65.90,21.500000,never smoked,0
1493,27013,Male,2.00,0,0,No,children,Urban,78.98,15.100000,Unknown,0
1494,7586,Male,24.00,0,0,No,Self-employed,Rural,111.33,29.600000,formerly smoked,0
1495,26452,Female,41.00,0,0,Yes,Private,Rural,104.36,30.200000,never smoked,0
1496,16378,Female,63.00,0,0,Yes,Govt_job,Urban,123.87,34.900000,Unknown,0
1497,5137,Male,64.00,0,0,Yes,Self-employed,Rural,210.00,30.700000,formerly smoked,0
1498,4559,Male,38.00,0,0,No,Private,Rural,86.86,36.500000,Unknown,0
1499,45357,Female,1.24,0,0,No,children,Rural,113.96,21.500000,Unknown,0

In [30]:
yp=ann.predict(sc.transform(ct.transform([["Male",67.0,0,1,"Yes","Private","Urban",228.69,36.600000,"formerly smoked"]])))

In [31]:
yp

array([[0.25383225]], dtype=float32)

In [51]:
yp>0.1

array([[False]])

In [39]:
yp=ann.predict(sc.transform(ct.transform([["Male",64.00,0,0,"Yes","Self-employed","Rural",210.00,30.700000,"formerly smoked"]])))

In [40]:
yp

array([[0.03143508]], dtype=float32)

In [47]:
yp>0.001

array([[False]])

In [48]:
yp=ann.predict(sc.transform(ct.transform([["Female",23.00,0,0,"No","Private","Rural",65.90,21.500000,"never smoked"]])))

In [49]:
yp

array([[0.00014944]], dtype=float32)

In [50]:
yp>0.0001

array([[ True]])